### ISSUE TITLE
Nothing to download on downloads page

### ISSUE THREAD

**Issue by starkgate** [mekberg/boar#115]
I'd like to thank you first for continuing to develop Boar. I've been using it for several years now and I'm happy to see it active once again.

I tried to download a build with the new commits, and it looks like the [downloads page](https://github.com/mekberg/boar/packages) doesn't really have anything I can download or build. Is it not set up yet? Or am I maybe missing something?

**Comment by mekberg** [comment]
Thank you! There are some downloads available under "releases". (Still no
new windows build since 2012, but at least that one is available and works
fine...) I'll readily admit I'm not entirely fluent in the github world,
there might be some oddities here and there after the BitBucket migration...

/Mats

**Comment by starkgate** [comment]
Will you add a new build at some point?

**Comment by mekberg** [comment]
That is certainly the idea. I'm still a bit wary since the conversion to
Python 3, it was quite... invasive. But everything looks good and all tests
works fine, I guess there's nothing stopping me really...

/Mats
